### ISSUE TITLE
Can't make it work

### ISSUE THREAD

**Issue by mopoIo** [adarhef/NowPlaying#1]
I downloaded the latest release and a lot of files were missing so I downloaded the source code, added the browser source, attached the index.html as a local file and nothing. I also tried using the url of the webpage instead of the local file and still no obs output.
When I open the index.html nothing pops up (after running the bat). From the system tray/the txt files it generates I can see Snip is working so I don't think that's the problem. Any ideas on what I should try?

**Comment by mopoIo** [comment]
Fixed it by moving from StreamElements SE.Live to the latest official OBS release on their github.

**Comment by adarhef** [comment]
> Fixed it by moving from StreamElements SE.Live to the latest official OBS release on their github.

Sorry for the confusion and glad you got things working!
The files that are missing are generally unneeded, unless you intend to run the widget in a browser and so you'd need one of the servers for that.
You should be able to just get the release with the Snip tool, and load it as a local file using the latest beta of OBS.
If you're not able to do that, let me know and I'll try to fix the release so people don't have trouble in the future :)

**Comment by mopoIo** [comment]
Yeah it was my fault for not reading your instructions carefully!
When I downloaded the latest release it didn't include Snip or the bat file that's why I had to download the source code instead. I did try just loading the index.html alone but it didn't work.
I'm very pepega so it's definitely my fault but thank you for replying!

**Comment by adarhef** [comment]
> Yeah it was my fault for not reading your instructions carefully!
> When I downloaded the latest release it didn't include Snip or the bat file that's why I had to download the source code instead. I did try just loading the index.html alone but it didn't work.
> I'm very pepega so it's definitely my fault but thank you for replying!

Thanks for letting me know! I changed the release to include Snip. I guess I haven't included it by accident (This is still a manual process unfortunately).
Though you shouldn't need the bat files. Just loading the widget as a local file in the OBS Browser Source and running Snip in the background should be enough. 
If it's not, please let me know. I'd like to figure it out :)

**Comment by mopoIo** [comment]
Oh yeah! I tried it without running the bat and it worked! Thank you!
