### ISSUE TITLE
Album Title & Hide after 10 seconds

### ISSUE THREAD

**Issue by BrillMatic** [adarhef/NowPlaying#2]
I'd love if there was a way to show album titles instead of artist title. Also, when streaming, the music player kind of gets in the way because it's always up. If there was a feature to hide it after 10 seconds of a song plays that would be great.

**Comment by adarhef** [comment]
Great suggestions, thank you!
I'll take a look soon and see what I can do.

**Comment by adarhef** [comment]
@BrillMatic 
Check out the new release I just added. If you have any questions or issues let me know.

**Comment by BrillMatic** [comment]
Wow it’s perfect! Thank you so much
